# Generated by Django 3.1.3 on 2020-11-07 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_remove_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.customer'),
        ),
    ]
