# Generated by Django 3.1.3 on 2020-11-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_quizmodal_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.customer'),
        ),
    ]
