# Generated by Django 3.1.3 on 2020-11-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20201110_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='name',
        ),
    ]
