# Generated by Django 3.1.3 on 2020-11-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20201111_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcare',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
