# Generated by Django 3.1.3 on 2020-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_auto_20201111_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
