# Generated by Django 3.1.3 on 2020-11-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_quizmodal_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('physical_activity', models.FloatField(default=0)),
                ('water_intake', models.FloatField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizapp.customer')),
            ],
        ),
    ]
