# Generated by Django 3.1.3 on 2020-11-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_concerns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concerns',
            name='category',
        ),
        migrations.AddField(
            model_name='concerns',
            name='category',
            field=models.ManyToManyField(related_name='concerns', to='quizapp.Category'),
        ),
        migrations.AlterField(
            model_name='concerns',
            name='is_primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='quizapp.category'),
        ),
    ]
