# Generated by Django 3.1.3 on 2020-11-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
